title : Découvrez les séjours à moins de 100km de chez vous ! - Weekendesk
description: Partout en France, découvrez les merveilles de notre pays en voyageant à proximité de chez vous. Surprises et souvenirs garantis !
encoding: utf-8
lang: FR-fr
author:
  name: Marie-Aline Millot
  email: mariealine@weekendesk.fr

google_analytics:
baseurl: ""
repo: "https://github.com/mariealine/100-km-jekyll-tailwind"
url: ""

# Build settings
plugins:
  - jekyll-postcss
  - jekyll-purgecss

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
# Merge with default excludes https://jekyllrb.com/docs/upgrading/3-to-4/#exclusion-changes
exclude:
  - "*.config.js"
  - netlify.toml
  - package.json
  - README.md
  - yarn.lock
